version: '2'
volumes:
    mongodb:
networks: 
    app:
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        networks:
            - app
    mongo-express:
        image: mongo-express 
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        networks:
            - app
        depends_on: 
            - mongo